# Small tests to confirm things are working.

command /bungeesktest:
   trigger:
      
      set network variable {test::*} to "one", "two"
      
      broadcast "%network variable {test::*}%"
      
      broadcast "%all bungeecord players%"

      loop all of the bungeecord players:
         message bungeecord player loop-proxyplayer the message "&7test"

      loop all of the online servers:
         broadcast "%loop-proxyserver%"
         message proxy server loop-proxyserver the message "message"

on player switch server:
   broadcast uuid of event-player

on server message "message":
   broadcast event-text
