package com.zulfen.zulfbungee.universal.socket.objects;

public enum PacketTypes {

    PLAYER_SEND_MESSAGE,
    BROADCAST_MESSAGE,
    PROXY_PLAYERS,
    PROXY_PLAYER_UUID,
    PROXY_PLAYER_PERMISSION,
    PROXY_PLAYER_IP,
    PLAYER_VIRTUAL_HOST,
    PLAYER_SERVER,
    PLAYER_SWITCH_SERVER,
    CONNECTION_NAME,
    PROXY_CLIENT_INFO,
    NETWORK_VARIABLE_MODIFY,
    NETWORK_VARIABLE_GET,
    PLAYER_ONLINE,
    SERVER_SWITCH_EVENT,
    SERVER_SEND_MESSAGE_EVENT,
    CONNECT_EVENT,
    DISCONNECT_EVENT,
    KICK_PLAYER,
    KICK_EVENT,
    INVALID_CONFIGURATION,
    GLOBAL_SCRIPT,
    PLAYER_EXECUTE_COMMAND,
    CONSOLE_EXECUTE_COMMAND,
    REGISTER_SERVER,
    DEREGISTER_SERVER,

}
