package tk.zulfengaming.zulfbungee.universal.socket;

public enum PacketTypes {

    PLAYER_SEND_MESSAGE,
    PROXY_PLAYERS,
    PLAYER_SERVER,
    HEARTBEAT,
    CLIENT_HANDSHAKE,
    CLIENT_INFO,
    NETWORK_VARIABLE_MODIFY,
    NETWORK_VARIABLE_GET,
    PLAYER_ONLINE,
    SERVER_SWITCH_EVENT,
    SERVER_SEND_MESSAGE_EVENT,
    CONNECT_EVENT,
    DISCONNECT_EVENT,
    KICK_EVENT,
    INVALID_CONFIGURATION

}
